apiVersion: v1
kind: Template
labels:
  application: settings
metadata:
  name: settings
  namespace: openshift
objects:

- apiVersion: user.openshift.io/v1
  groups: null
  identities:
  - anypassword:${USER_NAME}
  kind: User
  metadata:
    name: ${USER_NAME}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: registry-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${USER_NAME}


- apiVersion: security.openshift.io/v1
  kind: SecurityContextConstraints
  metadata:
    creationTimestamp: null
    name: anyuid
  fsGroup:
    type: RunAsAny
  groups:
  - system:cluster-admins
  requiredDropCapabilities:
  - MKNOD
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
  users:
  - system:serviceaccount:${APP_NAME}:default
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  defaultAddCapabilities: null
  allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegeEscalation: true
  allowPrivilegedContainer: false
  allowedCapabilities: null
  priority: 10
  readOnlyRootFilesystem: false

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    name: alpine
    namespace: openshift
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/alpine:3.10
      generation: 1
      importPolicy: {}
      name: "3.10"
      referencePolicy:
        type: Source



parameters:

- description: Add devops user to openshift
  displayName: Add devops user to openshift
  name: USER_NAME
  required: true
  value: devopsuser

- description: Add app name to openshift
  displayName: Add app name to openshift
  name: APP_NAME
  required: true
  value: thunder
    